services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: grpc-backend
    ports:
      - "9990:9090"
    networks:
      - grpc-net

  envoy:
    build: ./envoy
    container_name: grpc-envoy
    ports:
      - "8080:8080"
      - "9901:9901" # Admin
    depends_on:
      - backend
    networks:
      - grpc-net

  frontend:
    build: ./client
    container_name: grpc-frontend
    ports:
      - "4200:80"
    networks:
      - grpc-net

networks:
  grpc-net:
    driver: bridge
